name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Die Version der Komponente
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Vorbereitung
      - name: Entweder die Übergebene Version oder die aktuelle Version auslesen
        id: determine-version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      # Setup
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.determine-version.outputs.VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.read-properties.outputs.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Dpendencies installieren
        run: npm install

      - name: Versions-Tag in package.json schreiben
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.determine-version.outputs.VERSION }}\"/" package.json

      # Veröffentlichen
      - name: Veröffentlichen
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
